### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by KOliver94** [viclafouch/mui-tel-input#2]
Hi @viclafouch,

I really appreciate your work and I really like your `libphonenumber-js` based approach on this package. :rocket: I started to use it in my own project insted of `material-ui-phone-number`.

However, I noticed this package has quite a big footprint. It takes 342.09 KB of space in my project which is nearly as big as the whole `@mui` package. Do you think it's possible to reduce the size?

Thanks!

**Comment by viclafouch** [comment]
Hey @KOliver94 

Thank you for your feedback.

The reason why the package takes 340 KB is because `mui-tel-input` as you said, uses the `libphonenumber-js` library, which cost 150 KB. The use of this library allows to be sure to use the right formats, and to detect the right country depending on the format. 

I'm not a fan of using this source of truth :  `https://github.com/alexplumb/material-ui-phone-number/blob/master/src/country_data.js`. Using a dedicated library (and from Google) allows us to analyze, parse, and format in the right way, for sure. 

But I found 2 possible solutions to decrease the size : 

* Using css (like background-image and sprite) for flags (instead of base64). (Need confirmation and spike about that).
* Stop exporting `isValidPhoneNumber` from the package and ask the developer to install `libphonenumber-js` on his side.

I will look into these options in a future tense ;)
