### ISSUE TITLE
Feature Request: customize the unknown flag placeholder

### ISSUE THREAD

**Issue by JanMisker** [viclafouch/mui-tel-input#46]
In order to style this (awesome!!) input field a bit more, it would be nice if we can customize the 'no flag' / unknown flag placeholder. 

I see it is now imported statically on the level of the Flag component, so it's a bit tricky to see how to change it in a simple way.

**Comment by marciojuniors2** [comment]
up

**Comment by samiulla1111** [comment]
Yeah in Deployment mode 99% of Flags are not visible only placeholders are visible. In Development mode, this issue is not coming for any reason.
Please check the difference between both images of the deployment and development mode

Deployment mode:
![image](https://user-images.githubusercontent.com/44118231/232377679-cf5ce7b9-4fef-4d45-9400-9cd993adda63.png)

Development mode
![image](https://user-images.githubusercontent.com/44118231/232378091-4bedb34f-ff25-42dd-a4a9-c364cda82d68.png)

Can you please help me with that why it is coming like this?

**Comment by boschr** [comment]
You can achieve this with the new implemented `getFlagSource` attribute which is merged into the master branch today. You only have to wait for a new version to be released :)

**Comment by JanMisker** [comment]
Sounds good 👍

**Comment by viclafouch** [comment]
Hello !

This issue can be closed as a new release has been published with a new prop `unknownFlagElement`.

See : https://viclafouch.github.io/mui-tel-input/docs/api-reference/#unknownflagelement

Thanks everyone :)
